apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eira-api
      environment: production
      service: api
      project: eira
  template:
    metadata:
      labels:
        app: eira-api
        environment: production
        service: api
        project: eira
    spec:
      containers:
      - name: deployment_name-api
        image: azeiraacrp100.azurecr.io/eira/backend/api:latest
        envFrom:
        - secretRef:
            name: deployment_name-api
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "250Mi"
            cpu: "150m"
      restartPolicy: Always
  strategy:
    type: Recreate
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deployment_name-hpa
  namespace: eira
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment_name
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
