apiVersion: v1
kind: Service
metadata:
  name: deployment_name-svc
spec:
  selector:
    app: eira-api
    environment: production
    service: api
    project: eira
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
